module.exports = {
    citaDummy:[
        {
            id:1,
            fecha:"16/11/2021",
            hora_inicio:"9:00",
            hora_fin:"12:00",
            tipo:"consulta",
            id_usuario:1,
            id_mascota:1
        },
        {
            id:2,
            fecha:"16/11/2021",
            hora_inicio:"12:00",
            hora_fin:"13:00",
            tipo:"estetica",
            id_usuario:1,
            id_mascota:1
        }
    ]
}